/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {};

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    DailyReview: typeof import('./src/components/main-area/DailyReview.vue')['default'];
    ElAside: typeof import('element-plus/es')['ElAside'];
    ElButton: typeof import('element-plus/es')['ElButton'];
    ElCard: typeof import('element-plus/es')['ElCard'];
    ElCol: typeof import('element-plus/es')['ElCol'];
    ElContainer: typeof import('element-plus/es')['ElContainer'];
    ElIcon: typeof import('element-plus/es')['ElIcon'];
    ElInput: typeof import('element-plus/es')['ElInput'];
    ElMain: typeof import('element-plus/es')['ElMain'];
    ElMenu: typeof import('element-plus/es')['ElMenu'];
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem'];
    ElRow: typeof import('element-plus/es')['ElRow'];
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar'];
    ElTooltip: typeof import('element-plus/es')['ElTooltip'];
    EventLine: typeof import('./src/components/main-area/EventLine.vue')['default'];
    MainArea: typeof import('./src/components/main-area/MainArea.vue')['default'];
    MenuList: typeof import('./src/components/MenuList.vue')['default'];
    RouterLink: typeof import('vue-router')['RouterLink'];
    RouterView: typeof import('vue-router')['RouterView'];
    SideBar: typeof import('./src/components/SideBar.vue')['default'];
    SparkNote: typeof import('./src/components/main-area/SparkNote.vue')['default'];
    UserSetting: typeof import('./src/components/main-area/UserSetting.vue')['default'];
    WeeklyReview: typeof import('./src/components/main-area/WeeklyReview.vue')['default'];
  }
}
