/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    copy: typeof import('./src/components/main-area/SparkNote copy.vue')['default']
    DailyReview: typeof import('./src/components/main-area/DailyReview.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElectronVersions: typeof import('./src/components/ElectronVersions.vue')['default']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    EventLine: typeof import('./src/components/main-area/EventLine.vue')['default']
    MainArea: typeof import('./src/components/main-area/MainArea.vue')['default']
    Menu: typeof import('./src/components/Menu.vue')['default']
    MenuList: typeof import('./src/components/MenuList.vue')['default']
    ReactiveCounter: typeof import('./src/components/ReactiveCounter.vue')['default']
    ReactiveHash: typeof import('./src/components/ReactiveHash.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBar: typeof import('./src/components/SideBar.vue')['default']
    SparkNote: typeof import('./src/components/main-area/SparkNote.vue')['default']
    UserSetting: typeof import('./src/components/main-area/UserSetting.vue')['default']
    WeeklyReview: typeof import('./src/components/main-area/WeeklyReview.vue')['default']
  }
}
